title: VIXX Guide
author: Ya Boi
email: bigmac@domain.com
description: > # this means to ignore newlines until "baseurl:"
theme: minima

# social links
twitter_username: @badvixxmemes
github_username:  KenviTrash

show_excerpts: true # set to false to remove excerpts on the homepage
